### ISSUE TITLE
Suggestion: Dashboard view of posts by body/url

### ISSUE THREAD

**Issue by mstr3336** [krisives/cronnit.us#31]
I think it would be handy to be able to view one's posts based on the body of the post / the URL of the post, with a list of subs + their whentimes that could be expanded upon. 

As in- 

```yaml
- url: https://i.imgur.com/PRcD6vi.jpg
  # Display thumbnail if applicable
  latest_dttm: 2020-08-20T06:57:38Z
  posts: 
    - subreddit: aww
      title: Idk this is a title
      dttm: 2020-08-20T06:57:38Z
    - subreddit: memes
      title: Idk this is a title
      dttm: 2020-08-19T06:57:38Z
  # Inline form for submitting more, or link to "submit" form that prefills the body
```

I wonder if it would also be possible to incorporate historical, (potentially non cronnit-scheduled) posts for the user into this view, either via the reddit API (I don't know a tonne about the reddit API), or the pushift API, as in: https://api.pushshift.io/reddit/submission/search?html_decode=true&author=KayRice&size=1000

So possibly only querying future posts from cronnit, and querying historical posts from reddit itself.

I would anticipate that this view would be much less useful for text posts, which may have highly variable bodies, and more useful for link/image posts.

It could provide a really nice unified view of what a user has posted, where, and when, and what they have scheduled, as this is something that I struggle with in my scheduling workflow.
