### ISSUE TITLE
Improve thumbnail looks

### ISSUE THREAD

**Issue by MLanghof** [krisives/cronnit.us#37]
- [x] Use `img-thumbnail` class.

If needed:

- [ ] Look into `img-fluid` class.

**Comment by mstr3336** [comment]
Somewhat related I think it might be better if we were to handle the thumbnail rendering (as in, the html for thumbnail rendering) in the templates, by extracting thumbnail slugs (in php), and classifying the provenence, as in:

```
# Post
- id: 1
  thumbnail:
   content: anothergfycatslug
   src: gfycat
- id: 2
  thumbnail: # Text post
   slug: ~
   src: text_post
- id: 3
  thumbnail: # Link w/o thumb:
  slug: ~
  src: link
```

Using a twig template (probably separate from the view templates, and `{% include %}`'ed when needed.
