### ISSUE TITLE
Don't use raw in twig.

### ISSUE THREAD

**Issue by MLanghof** [krisives/cronnit.us#40]
Basically, the only way to get XSS'd in twig is to use `| raw`. We should not be doing any HTML arithmetic in PHP.

See also https://github.com/krisives/cronnit.us/issues/37#issuecomment-677449793 - I think that's indeed the way to do this.

**Comment by mstr3336** [comment]
I'm working on this now in https://github.com/mstr3336/cronnit.us/tree/post-view-safe-thumbs 

AFAIK, the best (that i can think of) mechanism is simply extracting out the various ids from URLs and storting these in array in `$post['thumb']` 

ie:

```yaml
# post
- id: 1
  body: https://i.imgur.com/9LDrmvP.png
  thumb: 
   src: imgur
   slug: 9LDrmvP
- id: 2
  body: https://gfycat.com/flusteredwangecko
  # Should also work for gfycat.com/watch , or redgifs.com (/watch/)
  thumb:
   src: gfycat
   slug: flusteredwangecko
```

the template will make some decisions based on the value of `thumb['type']`.

I'm also interested in using `twig` `{% block %}` tags to override some of the rendering aspects, so that  the rendering for our different views aren't as closely coupled.
